In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Wyckoff.csv',delimiter=':')

In [6]:
df

,1,P 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,1.0,a,1,"(x,y,z)",NaN,NaN,NaN
1,2,P -1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,2.0,i,1,"(x,y,z)","(-x,-y,-z)",NaN,NaN
3,NaN,NaN,1.0,h,-1,"(1/2,1/2,1/2)",NaN,NaN,NaN
4,NaN,NaN,1.0,g,-1,"(0,1/2,1/2)",NaN,NaN,NaN
5,NaN,NaN,1.0,f,-1,"(1/2,0,1/2)",NaN,NaN,NaN
6,NaN,NaN,1.0,e,-1,"(1/2,1/2,0)",NaN,NaN,NaN
7,NaN,NaN,1.0,d,-1,"(1/2,0,0)",NaN,NaN,NaN
8,NaN,NaN,1.0,c,-1,"(0,1/2,0)",NaN,NaN,NaN
9,NaN,NaN,1.0,b,-1,"(0,0,1/2)",NaN,NaN,NaN
10,NaN,NaN,1.0,a,-1,"(0,0,0)",NaN,NaN,NaN
11,3,P 1 2 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,2.0,e,1,"(x,y,z)","(-x,y,-z)",NaN,NaN
13,NaN,NaN,1.0,d,2,"(1/2,y,1/2)",NaN,NaN,NaN
14,NaN,NaN,1.0,c,2,"(1/2,y,0)",NaN,NaN,NaN
15,NaN,NaN,1.0,b,2,"(0,y,1/2)",NaN,NaN,NaN
16,NaN,NaN,1.0,a,2,"(0,y,0)",NaN,NaN,NaN
17,4,P 1 1 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,2.0,e,1,"(x,y,z)","(-x,-y,z)",NaN,NaN
19,NaN,NaN,1.0,d,2,"(1/2,1/2,z)",NaN,NaN,NaN
20,NaN,NaN,1.0,c,2,"(0,1/2,z)",NaN,NaN,NaN
21,NaN,NaN,1.0,b,2,"(1/2,0,z)",NaN,NaN,NaN
22,NaN,NaN,1.0,a,2,"(0,0,z)",NaN,NaN,NaN
23,5,P 2 1 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,2.0,e,1,"(x,y,z)","(x,-y,-z)",NaN,NaN
25,NaN,NaN,1.0,d,2,"(x,1/2,1/2)",NaN,NaN,NaN
26,NaN,NaN,1.0,c,2,"(x,0,1/2)",NaN,NaN,NaN
27,NaN,NaN,1.0,b,2,"(x,1/2,0)",NaN,NaN,NaN
28,NaN,NaN,1.0,a,2,"(x,0,0)",NaN,NaN,NaN
29,6,P 1 2sub1 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
5335,NaN,NaN,NaN,NaN,NaN,"(1/2,1/2,1/2)",NaN,NaN,NaN
5336,NaN,NaN,NaN,NaN,NaN,"(0,1/2,1/2)",NaN,NaN,NaN
5337,NaN,NaN,NaN,NaN,NaN,"(1/2,0,1/2)",NaN,NaN,NaN
5338,NaN,NaN,NaN,NaN,NaN,"(1/2,1/2,0)",NaN,NaN,NaN
5339,NaN,NaN,NaN,NaN,NaN,"(1/2,0,0)",NaN,NaN,NaN
5340,NaN,NaN,NaN,NaN,NaN,"(0,1/2,0)",NaN,NaN,NaN
5341,NaN,NaN,NaN,NaN,NaN,"(0,0,1/2)",NaN,NaN,NaN
5342,NaN,NaN,NaN,NaN,NaN,"(0,0,0)",NaN,NaN,NaN
5343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5344,NaN,NaN,NaN,NaN,NaN,"(x,y,z)","(-x,-y,-z)",NaN,NaN
5345,NaN,NaN,NaN,NaN,NaN,"(3/4,1/4,1/4)",NaN,NaN,NaN
5346,NaN,NaN,NaN,NaN,NaN,"(3/4,1/4,0)",NaN,NaN,NaN
5347,NaN,NaN,NaN,NaN,NaN,"(1/4,1/4,1/2)",NaN,NaN,NaN
5348,NaN,NaN,NaN,NaN,NaN,"(1/4,1/4,0)",NaN,NaN,NaN
5349,NaN,NaN,NaN,NaN,NaN,"(1/4,1/2,3/4)",NaN,NaN,NaN
5350,NaN,NaN,NaN,NaN,NaN,"(1/4,0,3/4)",NaN,NaN,NaN
5351,NaN,NaN,NaN,NaN,NaN,"(1/4,1/2,1/4)",NaN,NaN,NaN
5352,NaN,NaN,NaN,NaN,NaN,"(1/4,0,1/4)",NaN,NaN,NaN
5353,NaN,NaN,NaN,NaN,NaN,"(1/2,3/4,1/4)",NaN,NaN,NaN
5354,NaN,NaN,NaN,NaN,NaN,"(0,3/4,1/4)",NaN,NaN,NaN
5355,NaN,NaN,NaN,NaN,NaN,"(1/2,1/4,1/4)",NaN,NaN,NaN
5356,NaN,NaN,NaN,NaN,NaN,"(0,1/4,1/4)",NaN,NaN,NaN
5357,NaN,NaN,NaN,NaN,NaN,"(1/2,1/2,1/2)",NaN,NaN,NaN
5358,NaN,NaN,NaN,NaN,NaN,"(0,1/2,1/2)",NaN,NaN,NaN
5359,NaN,NaN,NaN,NaN,NaN,"(1/2,0,1/2)",NaN,NaN,NaN
5360,NaN,NaN,NaN,NaN,NaN,"(1/2,1/2,0)",NaN,NaN,NaN
5361,NaN,NaN,NaN,NaN,NaN,"(1/2,0,0)",NaN,NaN,NaN
5362,NaN,NaN,NaN,NaN,NaN,"(0,1/2,0)",NaN,NaN,NaN
5363,NaN,NaN,NaN,NaN,NaN,"(0,0,1/2)",NaN,NaN,NaN
5364,NaN,NaN,NaN,NaN,NaN,"(0,0,0)",NaN,NaN,NaN